const imgSrc = "./assets/images/webp/";

const bestSeller = [
  {
    soldOut: false,
    tags: { rank: 1, iwol: false, new: false, hot: false },
    imgs: {
      tireImg: `${imgSrc}tire/tire_kh_hp71_11_45degree.webp`,
      brandImg: `${imgSrc}logo/logo_kumho.webp`,
    },
    productInfo: { brand: "금호", title: "크루젠 HP71", model: "235/55R19" },
    price: { discount: 47, price: 125000 },
    review: { rate: 4.7, count: 2833 },
    keywords: { sagyejeol: "사계절용", suv: "SUV", gogeub: "고급형" },
    launchEvent: false,
  },
  {
    soldOut: false,
    tags: { rank: 2, iwol: false, new: false, hot: false },
    imgs: {
      tireImg: `${imgSrc}tire/tire_kh_ta91_1_45degree.webp`,
      brandImg: `${imgSrc}logo/logo_kumho.webp`,
    },
    productInfo: {
      brand: "금호",
      title: "마제스티9 솔루스 TA91",
      model: "245/45R18",
    },
    price: { discount: 46, price: 143500 },
    review: { rate: 4.8, count: 2288 },
    keywords: { sagyejeol: "사계절용", seungyong: "승용차", gogeub: "고급형" },
    launchEvent: false,
  },
  {
    soldOut: false,
    tags: { rank: 3, iwol: false, new: false, hot: false },
    imgs: {
      tireImg: `${imgSrc}tire/tire_hk_ventusS2AsH462_1_45degree.webp`,
      brandImg: `${imgSrc}logo/logo_hankook.webp`,
    },
    productInfo: {
      brand: "한국타이어",
      title: "벤투스 S2 AS",
      model: "245/45R18",
    },
    price: { discount: 42, price: 158100 },
    review: { rate: 4.8, count: 624 },
    keywords: { sagyejeol: "사계절용", seungyong: "승용차", gogeub: "고급형" },
    launchEvent: false,
  },
  {
    soldOut: false,
    tags: { rank: 4, iwol: false, new: false, hot: false },
    imgs: {
      tireImg: `${imgSrc}tire/tire_kh_hp71_11_45degree.webp`,
      brandImg: `${imgSrc}logo/logo_kumho.webp`,
    },
    productInfo: { brand: "금호", title: "크루젠 HP71", model: "225/55R18" },
    price: { discount: 47, price: 100900 },
    review: { rate: 4.7, count: 2840 },
    keywords: { sagyejeol: "사계절용", suv: "SUV", gogeub: "고급형" },
    launchEvent: false,
  },
  {
    soldOut: false,
    tags: { rank: 5, iwol: false, new: false, hot: false },
    imgs: {
      tireImg: `${imgSrc}tire/tire_kh_kl33_1_45degree.webp`,
      brandImg: `${imgSrc}logo/logo_kumho.webp`,
    },
    productInfo: {
      brand: "금호",
      title: "크루젠 프리미엄 KL33",
      model: "235/60R18",
    },
    price: { discount: 49, price: 112000 },
    review: { rate: 4.7, count: 1547 },
    keywords: { sagyejeol: "사계절용", suv: "SUV", gaseongbi: "가성비" },
    launchEvent: false,
  },
  {
    soldOut: false,
    tags: { rank: 6, iwol: false, new: false, hot: false },
    imgs: {
      tireImg: `${imgSrc}tire/tire_kh_ta91_1_45degree.webp`,
      brandImg: `${imgSrc}logo/logo_kumho.webp`,
    },
    productInfo: {
      brand: "금호",
      title: "마제스티9 솔루스 TA91",
      model: "225/55R17",
    },
    price: { discount: 45, price: 126400 },
    review: { rate: 4.8, count: 2288 },
    keywords: { sagyejeol: "사계절용", seungyong: "승용차", gogeub: "고급형" },
    launchEvent: false,
  },
  {
    soldOut: false,
    tags: { rank: 7, iwol: false, new: false, hot: false },
    imgs: {
      tireImg: `${imgSrc}tire/tire_kh_kl33_1_45degree.webp`,
      brandImg: `${imgSrc}logo/logo_kumho.webp`,
    },
    productInfo: {
      brand: "금호",
      title: "크루젠 프리미엄 KL33",
      model: "235/55R19",
    },
    price: { discount: 49, price: 106000 },
    review: { rate: 4.7, count: 1547 },
    keywords: { sagyejeol: "사계절용", suv: "SUV", gaseongbi: "가성비" },
    launchEvent: false,
  },
  {
    soldOut: false,
    tags: { rank: 8, iwol: false, new: false, hot: false },
    imgs: {
      tireImg: `${imgSrc}tire/tire_kh_hp71_11_45degree.webp`,
      brandImg: `${imgSrc}logo/logo_kumho.webp`,
    },
    productInfo: { brand: "금호", title: "크루젠 HP71", model: "235/60R18" },
    price: { discount: 46, price: 135000 },
    review: { rate: 4.7, count: 2840 },
    keywords: { sagyejeol: "사계절용", suv: "SUV", gogeub: "고급형" },
    launchEvent: false,
  },
  {
    soldOut: false,
    tags: { rank: 9, iwol: false, new: false, hot: false },
    imgs: {
      tireImg: `${imgSrc}tire/tire_ns_ah8_1_45degree.webp`,
      brandImg: `${imgSrc}logo/logo_nexen.webp`,
    },
    productInfo: { brand: "넥센", title: "엔프리즈 AH8", model: "245/45R18" },
    price: { discount: 50, price: 91000 },
    review: { rate: 4.7, count: 1225 },
    keywords: {
      sagyejeol: "사계절용",
      seungyong: "승용차",
      gaseongbi: "가성비",
    },
    launchEvent: false,
  },
  {
    soldOut: false,
    tags: { rank: 10, iwol: false, new: false, hot: false },
    imgs: {
      tireImg: `${imgSrc}tire/tire_kh_ta91_1_45degree.webp`,
      brandImg: `${imgSrc}logo/logo_kumho.webp`,
    },
    productInfo: {
      brand: "금호",
      title: "마제스티9 솔루스 TA91",
      model: "235/45R18",
    },
    price: { discount: 44, price: 142500 },
    review: { rate: 4.8, count: 2288 },
    keywords: { sagyejeol: "사계절용", seungyong: "승용차", gogeub: "고급형" },
    launchEvent: false,
  },
];
const lowestPrice = [
  {
    soldOut: false,
    tags: { rank: null, iwol: false, new: false, hot: false },
    imgs: {
      tireImg: `${imgSrc}tire/tire_ns_iqseries1_1_45degree.webp`,
      brandImg: `${imgSrc}logo/logo_nexen.webp`,
    },
    productInfo: { brand: "넥센", title: "I.Q series 1", model: "175/50R15" },
    price: { discount: 47, price: 44000 },
    review: { rate: 4.7, count: 354 },
    keywords: { sagyejeol: "사계절용", seungyong: "승용차", jeolyag: "절약형" },
    launchEvent: false,
  },
  {
    soldOut: false,
    tags: { rank: null, iwol: false, new: false, hot: false },
    imgs: {
      tireImg: `${imgSrc}tire/tire_kh_ta31_1_45degree.webp`,
      brandImg: `${imgSrc}logo/logo_kumho.webp`,
    },
    productInfo: { brand: "금호", title: "솔루스 TA31", model: "165/60R14" },
    price: { discount: 51, price: 48000 },
    review: { rate: 4.6, count: 2936 },
    keywords: {
      sagyejeol: "사계절용",
      seungyong: "승용차",
      gaseongbi: "가성비",
    },
    launchEvent: false,
  },
  {
    soldOut: false,
    tags: { rank: null, iwol: false, new: false, hot: false },
    imgs: {
      tireImg: `${imgSrc}tire/tire_kh_ta31_1_45degree.webp`,
      brandImg: `${imgSrc}logo/logo_kumho.webp`,
    },
    productInfo: { brand: "금호", title: "솔루스 TA31", model: "175/65R14" },
    price: { discount: 48, price: 51000 },
    review: { rate: 4.6, count: 2936 },
    keywords: {
      sagyejeol: "사계절용",
      seungyong: "승용차",
      gaseongbi: "가성비",
    },
    launchEvent: false,
  },
  {
    soldOut: false,
    tags: { rank: null, iwol: true, new: false, hot: false },
    imgs: {
      tireImg: `${imgSrc}tire/tire_2024_1_449ah3fecf5f6.webp`,
      brandImg: `${imgSrc}logo/logo_hankook.webp`,
    },
    productInfo: {
      brand: "한국타이어",
      title: "키너지EX H308",
      model: "195/60R14",
    },
    price: { discount: 47, price: 51200 },
    review: { rate: 4.6, count: 564 },
    keywords: {
      seungyong: "승용차",
      sagyejeol: "사계절용",
      gaseongbi: "가성비",
      pumjeol: 4,
    },
    launchEvent: false,
  },
  {
    soldOut: false,
    tags: { rank: null, iwol: false, new: false, hot: false },
    imgs: {
      tireImg: `${imgSrc}tire/tire_2022_12_1b60ha264ah9hf.webp`,
      brandImg: `${imgSrc}logo/logo_kumho.webp`,
    },
    productInfo: { brand: "금호", title: "포트란 KC55 (8P)", model: "145R13" },
    price: { discount: 28, price: 53500 },
    review: { rate: 4.4, count: 10 },
    keywords: {
      sagyejeol: "사계절용",
      gaseongbi: "가성비",
      poteoBack: "포터_뒤",
    },
    launchEvent: false,
  },
  {
    soldOut: false,
    tags: { rank: null, iwol: false, new: false, hot: false },
    imgs: {
      tireImg: `${imgSrc}tire/tire_kh_ta31_1_45degree.webp`,
      brandImg: `${imgSrc}logo/logo_kumho.webp`,
    },
    productInfo: { brand: "금호", title: "솔루스 TA31", model: "175/50R15" },
    price: { discount: 55, price: 55000 },
    review: { rate: 4.6, count: 2936 },
    keywords: {
      sagyejeol: "사계절용",
      seungyong: "승용차",
      gaseongbi: "가성비",
    },
    launchEvent: false,
  },
];
const risingProduct = [
  {
    productImg: `${imgSrc}oil-battery/pack_2023_8_18je6255f1dceh.webp`,
    brandImg: `${imgSrc}logo/logo_renault.webp`,
    brand: "르노코리아자동차",
    title: "르노코리아 순정 패키지",
    price: 31700,
    description: "르노 서비스센터보다 저렴한 순정 패키지",
  },
  {
    productImg: `${imgSrc}oil-battery/pack_2023_8_9dbfe579011ebb.webp`,
    brandImg: `${imgSrc}logo/logo_castrol.webp`,
    brand: "캐스트롤",
    title: "캐스트롤 GTX 패키지",
    price: 23600,
    description: "이 가격에 어디에도 없는 100% 합성유 패키지",
  },
  {
    productImg: `${imgSrc}oil-battery/pack_2023_10_24dii3hcei48959.webp`,
    brandImg: `${imgSrc}logo/logo_kg.webp`,
    brand: "KG모빌리티",
    title: "KG모빌리티(쌍용) 순정 패키지",
    price: 30000,
    description: "KG모빌리티 서비스센터보다 저렴한 순정 패키지",
  },
  {
    productImg: `${imgSrc}oil-battery/pack_2023_8_1845dibhfd1h32i.webp`,
    brandImg: `${imgSrc}logo/logo_mobis.webp`,
    brand: "현대모비스",
    title: "현대모비스 순정 패키지",
    price: 34400,
    description: "공식 서비스센터보다 저렴한 순정 패키지",
  },
  {
    productImg: `${imgSrc}oil-battery/pack_2023_8_9f89h0eh269j35.webp`,
    brandImg: `${imgSrc}logo/logo_castrol.webp`,
    brand: "캐스트롤",
    title: "캐스트롤 MAGNATEC 패키지",
    price: 30200,
    description: "부드럽고 정숙한 엔진오일을 원한다면 이 패키지",
  },
  {
    productImg: `${imgSrc}oil-battery/battery_df40l_front.webp`,
    brandImg: `${imgSrc}logo/logo_delkor.webp`,
    brand: "델코",
    title: "DF40L",
    price: 47000,
    description: "지금 주문하면 전국 어디든 2시간 이내로 출동",
  },
];
const winter = [
  {
    soldOut: false,
    tags: { rank: null, iwol: false, new: true, hot: false },
    imgs: {
      tireImg: `${imgSrc}tire/tire_ns_iqseries1_1_45degree.webp`,
      brandImg: `${imgSrc}logo/logo_bridge.webp`,
    },
    productInfo: {
      brand: "브리지스톤",
      title: "듀얼러 H/L400",
      model: "235/55R19",
    },
    price: { discount: 49, price: 124000 },
    review: { rate: null, count: null },
    keywords: { suv: "SUV", sagyejeol: "사계절용", gogeub: "고급형" },
    launchEvent: true,
  },
  {
    soldOut: false,
    tags: { rank: null, iwol: false, new: false, hot: false },
    imgs: {
      tireImg: `${imgSrc}tire/tire_ns_gtx_1_45degree.webp`,
      brandImg: `${imgSrc}logo/logo_nexen.webp`,
    },
    productInfo: { brand: "넥센", title: "로디안 GTX", model: "235/55R19" },
    price: { discount: 52, price: 97000 },
    review: { rate: 4.7, count: 659 },
    keywords: { sagyejeol: "사계절용", suv: "SUV", gaseongbi: "가성비" },
    launchEvent: false,
  },
  {
    soldOut: false,
    tags: { rank: null, iwol: false, new: true, hot: false },
    imgs: {
      tireImg: `${imgSrc}tire/tire_kh_ta31_1_45degree.webp`,
      brandImg: `${imgSrc}logo/logo_kumho.webp`,
    },
    productInfo: { brand: "금호", title: "솔루스 TA31", model: "225/55R17" },
    price: { discount: 43, price: 103000 },
    review: { rate: 4.8, count: 243 },
    keywords: {
      sagyejeol: "사계절용",
      seungyong: "승용차",
      seungchagam: "승차감",
    },
    launchEvent: false,
  },
  {
    soldOut: false,
    tags: { rank: null, iwol: false, new: true, hot: false },
    imgs: {
      tireImg: `${imgSrc}tire/tire_2024_3_1480ac65dj5d543.webp`,
      brandImg: `${imgSrc}logo/logo_pirelli.webp`,
    },
    productInfo: {
      brand: "피렐리",
      title: "P ZERO AS(그랜저GN7 OE)",
      model: "245/40R20",
    },
    price: { discount: 54, price: 250000 },
    review: { rate: 4.7, count: 38 },
    keywords: { sagyejeol: "사계절용", gogeub: "고급형", geulaenjeo: "그랜저" },
    launchEvent: false,
  },
];
const women = [
  {
    soldOut: false,
    tags: { rank: null, iwol: false, new: false, hot: false },
    imgs: {
      tireImg: `${imgSrc}tire/tire_kh_ku27_1_45degree.webp`,
      brandImg: `${imgSrc}logo/logo_kumho.webp`,
    },
    productInfo: { brand: "금호", title: "엑스타 LX KU27", model: "245/45R18" },
    price: { discount: 52, price: 92600 },
    review: { rate: 4.5, count: 3418 },
    keywords: {
      sagyejeol: "사계절용",
      seungyong: "승용차",
      jeolyag: "절약형",
      pumjeol: 4,
    },
    launchEvent: false,
  },
  {
    soldOut: false,
    tags: { rank: null, iwol: false, new: false, hot: true },
    imgs: {
      tireImg: `${imgSrc}tire/tire_br_turanzaSerenityPlus_1_45degree.webp`,
      brandImg: `${imgSrc}logo/logo_bridge.webp`,
    },
    productInfo: {
      brand: "브리지스톤",
      title: "투란자 세레니티 플러스",
      model: "245/45R18",
    },
    price: { discount: 53, price: 139000 },
    review: { rate: 4.7, count: 915 },
    keywords: {
      sagyejeol: "사계절용",
      seungyong: "승용차",
      gaseongbi: "가성비",
    },
    launchEvent: false,
  },
  {
    soldOut: true,
    tags: { rank: null, iwol: false, new: false, hot: false },
    imgs: {
      tireImg: `${imgSrc}tire/tire_hk_kinergyComfortH308_1_45degree.webp`,
      brandImg: `${imgSrc}logo/logo_hankook.webp`,
    },
    productInfo: {
      brand: "한국타이어",
      title: "키너지 EX",
      model: "165/65R14",
    },
    price: { discount: 43, price: 45900 },
    review: { rate: 4.6, count: 564 },
    keywords: {
      sagyejeol: "사계절용",
      seungyong: "승용차",
      gaseongbi: "가성비",
    },
    launchEvent: false,
  },
  {
    soldOut: false,
    tags: { rank: null, iwol: false, new: false, hot: false },
    imgs: {
      tireImg: `${imgSrc}tire/tire_ns_iqseries1_1_45degree.webp`,
      brandImg: `${imgSrc}logo/logo_nexen.webp`,
    },
    productInfo: { brand: "넥센", title: "I.Q series 1", model: "175/50R15" },
    price: { discount: 47, price: 44000 },
    review: { rate: 4.7, count: 354 },
    keywords: { sagyejeol: "사계절용", seungyong: "승용차", jeolyag: "절약형" },
    launchEvent: false,
  },
];
const wiper = [
  {
    soldOut: false,
    tags: { rank: null, iwol: false, new: false, hot: false },
    imgs: {
      tireImg: `${imgSrc}wiper/wiper_2023_12_139je1h44aa9h.webp`,
      brandImg: `${imgSrc}logo/logo_bosch.webp`,
    },
    productInfo: {
      brand: "BOSCH",
      title: "Clearfit",
      model: "보쉬 클리어핏 V4 CLEARFIT 와이퍼",
    },
    price: { discount: 74, price: 2800 },
    review: { rate: 4.8, count: 60 },
    keywords: { ilban: "일반형", unjeonjosu: "운전석+조수석" },
    launchEvent: false,
  },
  {
    soldOut: false,
    tags: { rank: null, iwol: false, new: false, hot: false },
    imgs: {
      tireImg: `${imgSrc}wiper/wiper_2023_12_137a702ggjj2456.webp`,
      brandImg: `${imgSrc}logo/logo_bosch.webp`,
    },
    productInfo: {
      brand: "BOSCH",
      title: "Aerotwin",
      model: "보쉬 에어로트윈 AEROTWIN 2S2 와이퍼",
    },
    price: { discount: 74, price: 14400 },
    review: { rate: 4.9, count: 32 },
    keywords: { ilban: "일반형", unjeonjosu: "운전석+조수석" },
    launchEvent: false,
  },
  {
    soldOut: false,
    tags: { rank: null, iwol: false, new: false, hot: false },
    imgs: {
      tireImg: `${imgSrc}wiper/wiper_2023_12_13cc3824e74f646.webp`,
      brandImg: `${imgSrc}logo/logo_michelin.webp`,
    },
    productInfo: {
      brand: "미쉐린",
      title: "RADIUS",
      model: "미쉐린 라디우스 RADIUS 하이브리드 와이퍼",
    },
    price: { discount: 16, price: 24800 },
    review: { rate: 4.9, count: 23 },
    keywords: { haibeulideu: "하이브리드", unjeonjosu: "운전석+조수석" },
    launchEvent: false,
  },
];
const storage = [
  {
    soldOut: false,
    tags: { rank: null, iwol: true, new: false, hot: false },
    imgs: {
      tireImg: `${imgSrc}tire/tire_2024_2_20ieg6fa48h87ad.webp`,
      brandImg: `${imgSrc}logo/logo_kumho.webp`,
    },
    productInfo: {
      brand: "금호",
      title: "크루젠 프리미엄 KL33",
      model: "235/55R17",
    },
    price: { discount: 48, price: 98800 },
    review: { rate: 4.7, count: 1569 },
    keywords: {
      suv: "SUV",
      sagyejeol: "사계절용",
      gaseongbi: "가성비",
      pumjeol: 1,
    },
    launchEvent: false,
  },
  {
    soldOut: false,
    tags: { rank: null, iwol: true, new: false, hot: false },
    imgs: {
      tireImg: `${imgSrc}tire/tire_2024_1_4ggdd56b62ee6.webp`,
      brandImg: `${imgSrc}logo/logo_nexen.webp`,
    },
    productInfo: { brand: "넥센", title: "로디안 GTX", model: "235/75R15" },
    price: { discount: 50, price: 65700 },
    review: { rate: 4.7, count: 659 },
    keywords: {
      suv: "SUV",
      sagyejeol: "사계절용",
      gaseongbi: "가성비",
      pumjeol: 1,
    },
    launchEvent: false,
  },
  {
    soldOut: false,
    tags: { rank: null, iwol: true, new: false, hot: false },
    imgs: {
      tireImg: `${imgSrc}tire/tire_2024_2_20ij06g2g54c1ce.webp`,
      brandImg: `${imgSrc}logo/logo_hankook.webp`,
    },
    productInfo: {
      brand: "한국타이어",
      title: "벤투스 S2 AS",
      model: "255/45R18",
    },
    price: { discount: 44, price: 157900 },
    review: { rate: 4.8, count: 638 },
    keywords: {
      seungyong: "승용차",
      sagyejeol: "사계절용",
      gogeub: "고급형",
      pumjeol: 3,
    },
    launchEvent: false,
  },
  {
    soldOut: false,
    tags: { rank: null, iwol: true, new: false, hot: false },
    imgs: {
      tireImg: `${imgSrc}tire/tire_2024_2_2674c4j4f0757he.webp`,
      brandImg: `${imgSrc}logo/logo_kumho.webp`,
    },
    productInfo: { brand: "금호", title: "크루젠 HP51", model: "235/55R18" },
    price: { discount: 50, price: 96900 },
    review: { rate: 4.7, count: 33 },
    keywords: { gogeub: "고급형", sagyejeol: "사계절용", suv: "SUV" },
    launchEvent: false,
  },
];

export {
  bestSeller,
  lowestPrice,
  risingProduct,
  winter,
  women,
  wiper,
  storage,
};
