const imgSrc = "./assets/images/webp/";

const bestSeller = [
  {
    rank: 1,
    tireImg: `${imgSrc}tire/tire_kh_hp71_11_45degree.webp`,
    brandImg: `${imgSrc}logo/logo_kumho.webp`,
    brand: "금호",
    title: "크루젠 HP71",
    model: "235/55R19",
    discount: 47,
    price: 125000,
    rate: 4.7,
    review: 2833,
    keywords: { 1: "사계절용", 2: "SUV", 3: "고급형" },
  },
  {
    rank: 2,
    tireImg: `${imgSrc}tire/tire_kh_ta91_1_45degree.webp`,
    brandImg: `${imgSrc}logo/logo_kumho.webp`,
    brand: "금호",
    title: "마제스티9 솔루스 TA91",
    model: "245/45R18",
    discount: 46,
    price: 143500,
    rate: 4.8,
    review: 2288,
    keywords: { 1: "사계절용", 2: "승용차", 3: "고급형" },
  },
  {
    rank: 3,
    tireImg: `${imgSrc}tire/tire_hk_ventusS2AsH462_1_45degree.webp`,
    brandImg: `${imgSrc}logo/logo_hankook.webp`,
    brand: "한국타이어",
    title: "벤투스 S2 AS",
    model: "245/45R18",
    discount: 42,
    price: 158100,
    rate: 4.8,
    review: 624,
    keywords: { 1: "사계절용", 2: "승용차", 3: "고급형" },
  },
  {
    rank: 4,
    tireImg: `${imgSrc}tire/tire_kh_hp71_11_45degree.webp`,
    brandImg: `${imgSrc}logo/logo_kumho.webp`,
    brand: "금호",
    title: "크루젠 HP71",
    model: "225/55R18",
    discount: 47,
    price: 100900,
    rate: 4.7,
    review: 2840,
    keywords: { 1: "사계절용", 2: "SUV", 3: "고급형" },
  },
  {
    rank: 5,
    tireImg: `${imgSrc}tire/tire_kh_kl33_1_45degree.webp`,
    brandImg: `${imgSrc}logo/logo_kumho.webp`,
    brand: "금호",
    title: "크루젠 프리미엄 KL33",
    model: "235/60R18",
    discount: 49,
    price: 112000,
    rate: 4.7,
    review: 1547,
    keywords: { 1: "사계절용", 2: "SUV", 3: "가성비" },
  },
  {
    rank: 6,
    tireImg: `${imgSrc}tire/tire_kh_ta91_1_45degree.webp`,
    brandImg: `${imgSrc}logo/logo_kumho.webp`,
    brand: "금호",
    title: "마제스티9 솔루스 TA91",
    model: "225/55R17",
    discount: 45,
    price: 126400,
    rate: 4.8,
    review: 2288,
    keywords: { 1: "사계절용", 2: "승용차", 3: "고급형" },
  },
  {
    rank: 7,
    tireImg: `${imgSrc}tire/tire_kh_kl33_1_45degree.webp`,
    brandImg: `${imgSrc}logo/logo_kumho.webp`,
    brand: "금호",
    title: "크루젠 프리미엄 KL33",
    model: "235/55R19",
    discount: 49,
    price: 106000,
    rate: 4.7,
    review: 1547,
    keywords: { 1: "사계절용", 2: "SUV", 3: "가성비" },
  },
  {
    rank: 8,
    tireImg: `${imgSrc}tire/tire_kh_hp71_11_45degree.webp`,
    brandImg: `${imgSrc}logo/logo_kumho.webp`,
    brand: "금호",
    title: "크루젠 HP71",
    model: "235/60R18",
    discount: 46,
    price: 135000,
    rate: 4.7,
    review: 2840,
    keywords: { 1: "사계절용", 2: "SUV", 3: "고급형" },
  },
  {
    rank: 9,
    tireImg: `${imgSrc}tire/tire_ns_ah8_1_45degree.webp`,
    brandImg: `${imgSrc}logo/logo_nexen.webp`,
    brand: "넥센",
    title: "엔프리즈 AH8",
    model: "245/45R18",
    discount: 50,
    price: 91000,
    rate: 4.7,
    review: 1225,
    keywords: { 1: "사계절용", 2: "승용차", 3: "가성비" },
  },
  {
    rank: 10,
    tireImg: `${imgSrc}tire/tire_kh_ta91_1_45degree.webp`,
    brandImg: `${imgSrc}logo/logo_kumho.webp`,
    brand: "금호",
    title: "마제스티9 솔루스 TA91",
    model: "235/45R18",
    discount: 44,
    price: 142500,
    rate: 4.8,
    review: 2288,
    keywords: { 1: "사계절용", 2: "승용차", 3: "고급형" },
  },
];
const lowestPrice = [
  {
    iwol: false,
    tireImg: `${imgSrc}tire/tire_ns_iqseries1_1_45degree.webp`,
    brandImg: `${imgSrc}logo/logo_nexen.webp`,
    brand: "넥센",
    title: "I.Q series 1",
    model: "175/50R15",
    discount: 47,
    price: 44000,
    rate: 4.7,
    review: 354,
    keywords: { 1: "사계절용", 2: "승용차", 3: "절약형" },
  },
  {
    iwol: false,
    tireImg: `${imgSrc}tire/tire_kh_ta31_1_45degree.webp`,
    brandImg: `${imgSrc}logo/logo_kumho.webp`,
    brand: "금호",
    title: "솔루스 TA31",
    model: "165/60R14",
    discount: 51,
    price: 48000,
    rate: 4.6,
    review: 2936,
    keywords: { 1: "사계절용", 2: "승용차", 3: "가성비" },
  },
  {
    iwol: false,
    tireImg: `${imgSrc}tire/tire_kh_ta31_1_45degree.webp`,
    brandImg: `${imgSrc}logo/logo_kumho.webp`,
    brand: "금호",
    title: "솔루스 TA31",
    model: "175/65R14",
    discount: 48,
    price: 51000,
    rate: 4.6,
    review: 2936,
    keywords: { 1: "사계절용", 2: "승용차", 3: "가성비" },
  },
  {
    iwol: true,
    tireImg: `${imgSrc}tire/tire_2024_1_449ah3fecf5f6.webp`,
    brandImg: `${imgSrc}logo/logo_hankook.webp`,
    brand: "한국타이어",
    title: "키너지EX H308",
    model: "195/60R14",
    discount: 47,
    price: 51200,
    rate: 4.6,
    review: 564,
    keywords: {
      1: "승용차",
      2: "사계절용",
      3: "가성비",
      4: "품절임박 잔여 4개",
    },
  },
  {
    iwol: false,
    tireImg: `${imgSrc}tire/tire_2022_12_1b60ha264ah9hf.webp`,
    brandImg: `${imgSrc}logo/logo_kumho.webp`,
    brand: "금호",
    title: "포트란 KC55 (8P)",
    model: "145R13",
    discount: 28,
    price: 53500,
    rate: 4.4,
    review: 10,
    keywords: { 1: "사계절용", 2: "가성비", 3: "포터_뒤" },
  },
  {
    iwol: false,
    tireImg: `${imgSrc}tire/tire_kh_ta31_1_45degree.webp`,
    brandImg: `${imgSrc}logo/logo_kumho.webp`,
    brand: "금호",
    title: "솔루스 TA31",
    model: "175/50R15",
    discount: 55,
    price: 55000,
    rate: 4.6,
    review: 2936,
    keywords: { 1: "사계절용", 2: "승용차", 3: "가성비" },
  },
];
const risingProduct = [
  {
    productImg: `${imgSrc}oil-battery/pack_2023_8_18je6255f1dceh.webp`,
    brandImg: `${imgSrc}logo/logo_renault.webp`,
    brand: "르노코리아자동차",
    title: "르노코리아 순정 패키지",
    price: 31700,
    description: "르노 서비스센터보다 저렴한 순정 패키지",
  },
  {
    productImg: `${imgSrc}oil-battery/pack_2023_8_9dbfe579011ebb.webp`,
    brandImg: `${imgSrc}logo/logo_castrol.webp`,
    brand: "캐스트롤",
    title: "캐스트롤 GTX 패키지",
    price: 23600,
    description: "이 가격에 어디에도 없는 100% 합성유 패키지",
  },
  {
    productImg: `${imgSrc}oil-battery/pack_2023_10_24dii3hcei48959.webp`,
    brandImg: `${imgSrc}logo/logo_kg.webp`,
    brand: "KG모빌리티",
    title: "KG모빌리티(쌍용) 순정 패키지",
    price: 30000,
    description: "KG모빌리티 서비스센터보다 저렴한 순정 패키지",
  },
  {
    productImg: `${imgSrc}oil-battery/pack_2023_8_1845dibhfd1h32i.webp`,
    brandImg: `${imgSrc}logo/logo_mobis.webp`,
    brand: "현대모비스",
    title: "현대모비스 순정 패키지",
    price: 34400,
    description: "공식 서비스센터보다 저렴한 순정 패키지",
  },
  {
    productImg: `${imgSrc}oil-battery/pack_2023_8_9f89h0eh269j35.webp`,
    brandImg: `${imgSrc}logo/logo_castrol.webp`,
    brand: "캐스트롤",
    title: "캐스트롤 MAGNATEC 패키지",
    price: 30200,
    description: "부드럽고 정숙한 엔진오일을 원한다면 이 패키지",
  },
  {
    productImg: `${imgSrc}oil-battery/battery_df40l_front.webp`,
    brandImg: `${imgSrc}logo/logo_delkor.webp`,
    brand: "델코",
    title: "DF40L",
    price: 47000,
    description: "지금 주문하면 전국 어디든 2시간 이내로 출동",
  },
];
const winter = [
  {
    new: true,
    tireImg: `${imgSrc}tire/tire_ns_iqseries1_1_45degree.webp`,
    brandImg: `${imgSrc}logo/logo_bridge.webp`,
    brand: "브리지스톤",
    title: "듀얼러 H/L400",
    model: "235/55R19",
    discount: 49,
    price: 124000,
    rate: null,
    review: null,
    keywords: { 1: "SUV", 2: "사계절", 3: "고급형" },
    launchEvent: true,
  },
  {
    new: false,
    tireImg: `${imgSrc}tire/tire_ns_gtx_1_45degree.webp`,
    brandImg: `${imgSrc}logo/logo_nexen.webp`,
    brand: "넥센",
    title: "로디안 GTX",
    model: "235/55R19",
    discount: 52,
    price: 97000,
    rate: 4.7,
    review: 659,
    keywords: { 1: "사계절용", 2: "SUV", 3: "가성비" },
    launchEvent: false,
  },
  {
    new: true,
    tireImg: `${imgSrc}tire/tire_kh_ta31_1_45degree.webp`,
    brandImg: `${imgSrc}logo/logo_kumho.webp`,
    brand: "금호",
    title: "솔루스 TA31",
    model: "225/55R17",
    discount: 43,
    price: 103000,
    rate: 4.8,
    review: 243,
    keywords: { 1: "사계절용", 2: "승용차", 3: "승차감" },
    launchEvent: false,
  },
  {
    new: true,
    tireImg: `${imgSrc}tire/tire_2024_3_1480ac65dj5d543.webp`,
    brandImg: `${imgSrc}logo/logo_pirelli.webp`,
    brand: "피렐리",
    title: "P ZERO AS(그랜저GN7 OE)",
    model: "245/40R20",
    discount: 54,
    price: 250000,
    rate: 4.7,
    review: 38,
    keywords: {
      1: "사계절용",
      2: "고급형",
      3: "그랜저",
    },
    launchEvent: false,
  },
];

export { bestSeller, lowestPrice, risingProduct, winter };
